[package]
name = "fuse_example"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
fuser = "0.16.0"
libc = "0.2.177"
rusqlite = "0.37.0"
uuid = "1.18.1"
